Disable kubewarden plugins test
`kubewarden-ui` fails with the following error:

```
Installing dependencies for kubewarden-ui

yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
(node:4124) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
[3/5] Fetching packages...
warning bare-fs@4.5.2: The engine "bare" appears to be invalid.
warning bare-os@3.6.2: The engine "bare" appears to be invalid.
warning chart.js@4.5.1: The engine "pnpm" appears to be invalid.
error @achrinza/node-ipc@9.2.9: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19 || 20 || 21 || 22". Got "24.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

In order for these to succeed, we will need to release a new version of shell that targets node 24 and update kubewarden to consume the new shell version.

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>