Strip quotes from auth and upload-cloud versions
This strips the quotes from the version strings for `google-github-actions/auth` and `google-github-actions/upload-cloud-storage`. The single quotes originally included the version comment, causing workflows to fail:

```
Error: Unable to resolve action `google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3`, unable to find version `7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3`. Unable to resolve action `google-github-actions/upload-cloud-storage@6397bd7208e18d13ba2619ee21b9873edc94427a # v3`, unable to find version `6397bd7208e18d13ba2619ee21b9873edc94427a # v3`
```

Signed-off-by: Phillip Rak <rak.phillip@gmail.com>